/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "realm.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->val, ~0))
		 return FALSE;
	return TRUE;
}
