/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REALM_H_RPCGEN
#define _REALM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct str_t {
	char *val;
};
typedef struct str_t str_t;

#define SCHANNEL_PROG 0x0
#define SCHANNEL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sign_kex 1
extern  str_t * sign_kex_1(str_t *, CLIENT *);
extern  str_t * sign_kex_1_svc(str_t *, struct svc_req *);
extern int schannel_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sign_kex 1
extern  str_t * sign_kex_1();
extern  str_t * sign_kex_1_svc();
extern int schannel_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);

#else /* K&R C */
extern bool_t xdr_str_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REALM_H_RPCGEN */
