/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "realm.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->str_t_val, (u_int *) &objp->str_t_len, 128))
		 return FALSE;
	return TRUE;
}
