/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "realm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include "sodium.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#define KEY_FILENAME "/key"

static char key[crypto_sign_SECRETKEYBYTES];

static int
read_key()
{
	FILE *file = NULL;
	int ok = -1;

	if (NULL == (file = fopen(KEY_FILENAME, "r"))) {
		die(1, "could not open file");
	}

	if (crypto_sign_SECRETKEYBYTES == fread(key, 1, crypto_sign_SECRETKEYBYTES, file)) {
		ok = 0;
	}

	fclose(file);
	return ok;
}

str_t * sign_kex_1_svc(str_t *arg, struct svc_req *) {
	static str_t res;
	int rv;

	while (!res.val) res.val = calloc(crypto_sign_ed25519_BYTES, sizeof(char));

	rv = crypto_sign(res.val, NULL, arg->val, 2*crypto_box_PUBLICKEYBYTES, key);

	return &res;
}

static void
schannel_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		str_t sign_kex_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case sign_kex:
		_xdr_argument = (xdrproc_t) xdr_str_t;
		_xdr_result = (xdrproc_t) xdr_str_t;
		local = (char *(*)(char *, struct svc_req *)) sign_kex_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static long strtolx(const char *arg)
{
	long value;
	char *end;

	value = strtol(arg, &end, 10);

	if (end != arg + strlen(arg)) {
        fprintf(stderr, "Invalid port was provided\n");
        exit(-1);
    }

	return value;
}

int
main (int argc, char **argv)
{
	int port;
	register struct rpcsvc *transp;

	die(0 != read_key(), "failed to read key from /key");

    if (argc != 2) {
        fprintf(stderr, "Usage: ./realm_server PORT\n");
    }
    port = strtolx(argv[1]);

	transp = svcvirt_create(port);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create virtio service.");
		exit(1);
	}
	svc_register(transp, schannel_prog_1);
	svc_run(transp);
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
